export const NEWS_DATA = [
  {
    id: 1,
    introText: "Test 1",
    postedBy: "test1@gmail.com",
    isUpdatedFromMobile: true,
    category: "Art",
    categoryId: 1,
    isPublished: true,
  },
  {
    id: 2,
    introText: "Test 2",
    postedBy: "test2@gmail.com",
    isUpdatedFromMobile: true,
    category: "None",
    categoryId: null,
    isPublished: true,
  },
  {
    id: 3,
    introText: "Random 1",
    postedBy: "random1@gmail.com",
    isUpdatedFromMobile: false,
    category: "None",
    categoryId: null,
    isPublished: true,
  },
  {
    id: 4,
    introText: "Random 2",
    postedBy: "random2@gmail.com",
    isUpdatedFromMobile: true,
    category: "Events",
    categoryId: 2,
    isPublished: true,
  },
  {
    id: 5,
    introText: "Random 3",
    postedBy: "random3@gmail.com",
    isUpdatedFromMobile: false,
    category: "Events",
    categoryId: 2,
    isPublished: false,
  },
  {
    id: 6,
    introText: "Random 4",
    postedBy: "random4@gmail.com",
    isUpdatedFromMobile: false,
    category: "Events",
    categoryId: 2,
    isPublished: true,
  },
];
